SET SERVEROUTPUT ON;
DECLARE
    V_TEXT VARCHAR2(50);
BEGIN
  DBMS_OUTPUT.PUT_LINE(V_TEXT);
END;

/* ASSIGN DEFAULT VALUE */
DECLARE
    V_TEXT VARCHAR2(50) NOT NULL DEFAULT 'HELLO';
BEGIN
  DBMS_OUTPUT.PUT_LINE(V_TEXT);
END;

/*ASSIGN VALUE FOR VARIABLE V_TEXT*/
DECLARE
    V_TEXT VARCHAR2(50) NOT NULL DEFAULT 'HELLO';
BEGIN
  V_TEXT := 'PL/SQL';  
  DBMS_OUTPUT.PUT_LINE(V_TEXT);
END;

/*CONCATENATION IN PLSQL*/

DECLARE
    V_TEXT VARCHAR2(50) NOT NULL DEFAULT 'WELCOME';
BEGIN
  V_TEXT := 'PL/SQL' || ' COURSE';  
  DBMS_OUTPUT.PUT_LINE(V_TEXT || ' BEGINNER TO ADVANCED');
END;

DECLARE
    V_TEXT VARCHAR2(50) NOT NULL := 'WELCOME';
BEGIN 
  DBMS_OUTPUT.PUT_LINE(V_TEXT || ' BEGINNER TO ADVANCED');
END;

/*NUMBER DATA TYPE*/

DECLARE
 V_NUMBER NUMBER NOT NULL := 50;
BEGIN 
 
 DBMS_OUTPUT.PUT_LINE(V_NUMBER||' BEGINNER TO ADVANCED');
END;

/*Using decimal*/
DECLARE
 V_NUMBER NUMBER NOT NULL := 50.42;
BEGIN 
 DBMS_OUTPUT.PUT_LINE(V_NUMBER||' BEGINNER TO ADVANCED');
END;

/*NOW GIVING NUMBER A MAXIMUM LENGTH AND ADDING PRECISION */

DECLARE
 V_NUM NUMBER(10,5) NOT NULL := 50.42;
BEGIN
    DBMS_OUTPUT.PUT_LINE(v_num || ' BEGINNER TO ADVANCED');
END;

/*PLS_INTEGER DATATYPE */

DECLARE
 V_NUM PLS_INTEGER NOT NULL := 50;
BEGIN
    DBMS_OUTPUT.PUT_LINE(v_num || ' BEGINNER TO ADVANCED');
END;

/*BINARY_INTEGER */

DECLARE
 V_NUM BINARY_INTEGER NOT NULL := 50;
BEGIN
    DBMS_OUTPUT.PUT_LINE(v_num || ' BEGINNER TO ADVANCED');
END;

/*BINARY_FLOAT DATATYPE */

DECLARE
 V_NUM BINARY_FLOAT NOT NULL := 50.42f;
BEGIN
    DBMS_OUTPUT.PUT_LINE(v_num || ' BEGINNER TO ADVANCED');
END;

/* SYSDATE DATATYPE */

DECLARE
 V_DATE DATE NOT NULL := SYSDATE;
BEGIN
    DBMS_OUTPUT.PUT_LINE(v_date || ' BEGINNER TO ADVANCED');
END;

/* SYSDATE DATATYPE */

DECLARE
 V_DATE DATE NOT NULL := '22-NOV-22 14:01:32';
BEGIN
    DBMS_OUTPUT.PUT_LINE(v_date || ' BEGINNER TO ADVANCED');
END;

/* TIMESTAMP DATATYPE */

DECLARE
 V_DATE TIMESTAMP NOT NULL := SYSTIMESTAMP;
BEGIN
    DBMS_OUTPUT.PUT_LINE(v_date || ' BEGINNER TO ADVANCED');
END;
DECLARE
 V_DATE DATE NOT NULL := SYSDATE;
BEGIN
    DBMS_OUTPUT.PUT_LINE(v_date || ' BEGINNER TO ADVANCED');
END;

/* TIMESTAMP WITH TIMEZONE DATATYPE */

DECLARE
 V_DATE TIMESTAMP WITH TIME ZONE NOT NULL := SYSTIMESTAMP;
BEGIN
    DBMS_OUTPUT.PUT_LINE(v_date || ' BEGINNER TO ADVANCED');
END;



/* TIMESTAMP WITH TIMEZONE DATATYPE ALONG WITH PRECISION*/

DECLARE
 V_DATE TIMESTAMP(3) WITH TIME ZONE NOT NULL := SYSTIMESTAMP;
BEGIN
    DBMS_OUTPUT.PUT_LINE(v_date || ' BEGINNER TO ADVANCED');
END;



/* INTERVAL DAY TO SECOND DATATYPE */

DECLARE
 V_DATE INTERVAL DAY(4) TO SECOND(2) := '24 02:05:21.012';
BEGIN
    DBMS_OUTPUT.PUT_LINE(v_date || ' BEGINNER TO ADVANCED');
END;

/* INTERVAL YEAR TO MONTH DATATYPE */

DECLARE
 V_DATE INTERVAL YEAR TO MONTH := '12-3';
BEGIN
    DBMS_OUTPUT.PUT_LINE(v_date || ' BEGINNER TO ADVANCED');
END;

/* INTERVAL YEAR TO MONTH DATATYPE ALONG WITH PREC */

DECLARE
 V_DATE INTERVAL YEAR(3) TO MONTH := '122-3';
BEGIN
    DBMS_OUTPUT.PUT_LINE(v_date || ' BEGINNER TO ADVANCED');
END;



/* BOOLEAN DATATYPE ONLY IN IF STATEMENTSS   */

DECLARE
 V_BOOL BOOLEAN:= TRUE;
BEGIN
    DBMS_OUTPUT.PUT_LINE(V_BOOL || ' BEGINNER TO ADVANCED');
END;

-----------------------===================-----------------------
-----------------------DECLARING VARIABLES-----------------------
-----------------------===================-----------------------
SET SERVEROUTPUT ON;
DECLARE 
    v varchar2(20) := 2 + 25 * 3;
BEGIN
    dbms_output.put_line(v);
END;
-----------------------===================-----------------------
DECLARE 
    v_text varchar2(50) NOT NULL DEFAULT 'Hello';
    v_number1 number := 50;
    v_number2 number(2) := 50.42;
    v_number3 number(10,2) := 50.42;
    v_number4 PLS_INTEGER := 50;
    v_number5 BINARY_float := 50.42;
    v_DATE1 DATE := '22-NOV-18 12:01:32';
    v_DATE2 timestamp := systimestamp;
    v_DATE3 timestamp(9) WITH TIME ZONE := systimestamp;
    v_DATE4 interval day(4) to second (3) := '124 02:05:21.012 ';
    v_DATE5 interval year to month := '12-3';
BEGIN
    V_TEXT := 'PL/SQL' || 'Course';
    DBMS_OUTPUT.PUT_LINE(V_TEXT);
    DBMS_OUTPUT.PUT_LINE(v_number1);
    DBMS_OUTPUT.PUT_LINE(v_number2);
    DBMS_OUTPUT.PUT_LINE(v_number3);
    DBMS_OUTPUT.PUT_LINE(v_number4);
    DBMS_OUTPUT.PUT_LINE(v_number5);
    DBMS_OUTPUT.PUT_LINE(v_DATE1);
    DBMS_OUTPUT.PUT_LINE(v_DATE2);
    DBMS_OUTPUT.PUT_LINE(v_DATE3);
    DBMS_OUTPUT.PUT_LINE(v_DATE4);
    DBMS_OUTPUT.PUT_LINE(v_DATE5);
    END;
----------------==================================---------------
----------------USING BOOLEAN DATA TYPE in PL/SQL----------------
----------------==================================---------------
DECLARE
    v_boolean boolean := true;
BEGIN
    dbms_output.put_line(sys.diutil.bool_to_int(v_boolean));
END;
----------------==================================---------------